<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>SteamDepotDownload.Steam</AssemblyName>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <BaseOutputPath>..\build\</BaseOutputPath>
    <OutputPath>$(BaseOutputPath)Release\SteamDepotDownload.Steam</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SteamDepotDownload.Tier0\SteamDepotDownload.Tier0.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="QRCoder" Version="1.8.0" />
    <PackageReference Include="SteamKit2" Version="3.4.0" />
    <PackageReference Include="VPKTools" Version="1.0.5" />
  </ItemGroup>

</Project>
